apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketsenseai-backend
  labels:
    app: marketsenseai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketsenseai-backend
  template:
    metadata:
      labels:
        app: marketsenseai-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/jait345/marketsenseai-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: marketsenseai-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: marketsenseai-secrets
                  key: JWT_SECRET
