apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketsenseai-backend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: marketsenseai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marketsenseai-backend
                port:
                  number: 80
