apiVersion: v1
kind: Service
metadata:
  name: marketsenseai-backend
  labels:
    app: marketsenseai-backend
spec:
  type: ClusterIP
  selector:
    app: marketsenseai-backend
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
